name=MaerklinMotorola
version=0.3.1
author=Laserlicht
maintainer=chatelao
sentence=Decoding the signals from the Märklin-Motorola-protocol.
paragraph=Support MM and MM2 protocols
category=Communication
url=https://github.com/chatelao/MaerklinMotorola
architectures=*
includes=MaerklinMotorola.h
