on:
- push
- pull_request

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples

    runs-on: ubuntu-latest # I picked Ubuntu to use shell scripts.

    strategy:
      matrix:
        board:
          - fqbn: arduino:avr:uno
            exclude: LocoMotor
          - fqbn: rp2040:rp2040:seeed_xiao_rp2040
            exclude: ""

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v3
        with:
          required-libraries: AccelStepper,Servo,DFRobotDFPlayerMini,U8g2,EncButton,DFPlayerMini_Fast,Adafruit NeoPixel
          platform-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          arduino-board-fqbn: ${{ matrix.board.fqbn }}
          sketch-names-exclude: ${{ matrix.board.exclude }}
